helloworld_test:
  image: helloworld
  ports:
    - "8001:8001"
  environment:
    - "CONSUL=consul:8500"
  links:
    - consul:consul
    - statsd:statsd
consul:
  image: progrium/consul
  ports:
    - "9400:8400"
    - "9500:8500"
    - "9600:53/udp"
  hostname: node1
  command: "-server -bootstrap -ui-dir /ui"
statsd:
  image: hopsoft/graphite-statsd
  ports:
    - "8080:80"
    - "2003:2003"
    - "8125:8125/udp"
    - "8126:8126"

