---
application_name: 'helloworld'
namespace: 'github.com/nicholasjackson'
generator_name: minke-generator-go
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  password: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  build_image: 'golang:latest'
  application_docker_file: './dockerfile/helloworld/'
  application_compose_file: './dockercompose/helloworld/docker-compose.yml'
fetch:
  enabled: true
test:
  enabled: true
build:
  post:
    copy:
      -
        from: '../helloworld'
        to: './dockerfile/helloworld'
      -
        from: './swagger_spec/swagger.yml'
        to: './dockerfile/helloworld/swagger_spec'
run:
  pre:
    consul_loader:
      config_file: './consul_keys.yml'
      url:
        address: consul
        port: 8500
        type: private
cucumber:
  pre:
    consul_loader:
      config_file: './consul_keys.yml'
      url:
        address: consul
        port: 8500
        type: private
    health_check:
      address: helloworld
      port: 8001
      path: /v1/health
      type: private
